// import { Inter } from 'next/font/google';
import './globals.css';
import Hero from '@/components/Hero';
import Header from '@/components/Header';
import Head from 'next/head';
import WeddingCountdown from '@/components/WeddingCountdown';
// const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet"
        />
      </Head>
      <body
        className={` mx-40 my-16 w-container rounded-xl bg-white text-black shadow-2xl flex flex-col items-center`}
      >
        <Hero />
        <Header />
        {children}
        <WeddingCountdown />
      </body>
    </html>
  );
}
